# NVIDIA NeMo Agent Toolkit 黑客松配置
# 支持用户自定义OpenAI兼容API

general:
  use_uvloop: true

functions:
  tavily_search:
    _type: tavily_internet_search
    description: "使用Tavily API进行实时网络搜索"
  
  current_datetime:
    _type: current_datetime
    description: "获取当前日期和时间"

  chart_mcp:
    _type: mcp_tool_wrapper
    url: "http://localhost:1122/mcp"
    transport: "streamable-http"
    mcp_tool_name: chart_mcp
    description: "Returns a chart visualization"
llms:
  # 默认使用Bailian API (用户可修改)
  default_llm:
    _type: openai
    model_name: "deepseek-ai/DeepSeek-V3.1"
    api_key: "sk-gmgvvnrcqbidtvdfqiqsxadrrgfwjwuialnrawzrohsihfby"
    base_url: "https://api.siliconflow.cn/v1"
    temperature: 0.7
    max_tokens: 2048

workflow:
  _type: react_agent
  tool_names:
    - tavily_search
    - current_datetime
    - chart_mcp
  llm_name: default_llm
  verbose: true
  parse_agent_response_max_retries: 3
  max_iterations: 10
